# Generated by roxytest: Do not edit by hand!

context("File R/read_write_create.R: @tests")

test_that("Function check_line_lengths() @ L77", {
  expect_error(check_line_lengths(c("the", "quick", "brown", "fox"), 4))
  expect_equal(check_line_lengths(c("the", "quick", "brown", "fox"), 5),
                                  c("the", "quick", "brown", "fox"))
})

