# Generated by roxytest: Do not edit by hand!

# File R/individual_names.R: @tests

test_that("Function add_indi_names_var() @ L69", {
  expect_snapshot_value(
                 gedcom(subm("Me")) %>% 
                 add_indi() %>% 
                 add_indi_names(name_pieces(given = "Joe", surname = "Bloggs")) %>% 
                 add_indi_names_var("Joe Bloggs", names_var = name_pieces(given = "JB"), 
                                    method = "tests", phonetic_variation = FALSE) %>% 
                 tidyged.internals::remove_dates_for_tests(), "json2")
})


test_that("Function remove_indi_name() @ L150", {
  expect_equal(gedcom(subm()) %>% 
                 add_indi(),
               gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi_names(name_pieces(given = "Joe", surname = "Bloggs")) %>% 
                 remove_indi_name("Joe Bloggs"))
})


test_that("Function remove_indi_name_var() @ L185", {
  expect_equal(gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi_names(name_pieces(given = "Joe", surname = "Bloggs")),
               gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi_names(name_pieces(given = "Joe", surname = "Bloggs")) %>% 
                 add_indi_names_var("Joe Bloggs", names_var = name_pieces(given = "Jo", surname = "Blogs"), 
                                    method = "spelling error") %>% 
                 remove_indi_name_var("Jo Blogs"))
})

