# Generated by roxytest: Do not edit by hand!


test_that("Function summary.tidyged() @ L18", {
  expect_snapshot_value(
                 gedcom(subm("Me"), gedcom_description = "descrip", language = "English",
                        gedcom_copyright = "copyright statement") %>% 
                  summary(), "json2")
})


test_that("Function str.tidyged() @ L64", {
  expect_snapshot_value(
   gedcom(subm("Me")) %>% 
    add_indi() %>% 
    add_indi() %>% 
    add_indi() %>% 
    add_famg() %>% 
    add_famg() %>% 
    add_media("ref1", "AAC") %>% 
    add_media("ref1", "AAC") %>% 
    add_sour() %>% 
    add_repo("repo") %>% 
    add_note("note1") %>% 
    add_note("note2") %>% 
    str(), "json2")
})


test_that("Function df_indi() @ L110", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_indi(sex = "M") %>% 
   add_indi_names(given = "Joe", surname = "Bloggs") %>% 
   add_indi_event_birth(event_date = date_calendar(year = 1950, month = 5, day = 7),
                              place_name = "Somewhere") %>% 
   add_indi_event_death(event_date = date_calendar(year = 2000, month = 12, day = 1),
                              place_name = "Somewhere else") %>% 
   add_indi(sex = "F") %>% 
   add_indi_names(given = "Jess", surname = "Bloggs") %>% 
   add_indi_event_birth(event_date = date_calendar(year = 1948, month = 1, day = 15),
                              place_name = "Somewhere") %>% 
   add_indi(sex = "F") %>% 
   add_indi_names(given = "Jessie", surname = "Bloggs") %>% 
   add_indi_event_birth(event_date = date_approximated(date_calendar(year = 1970), about = TRUE),
                              place_name = "Elsewhere") %>%
   add_famg(husband = "Joe", wife = "@I2@", children = "Jessie") %>% 
   add_famg_event_relationship(event_date = date_calendar(year = 1969, month = 1, day = 30),
                                 place_name = "Another place") %>% 
   tidyged.internals::remove_dates_for_tests() %>% 
   df_indi(), "json2")
})


test_that("Function df_famg() @ L168", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_indi(sex = "M") %>% 
   add_indi_names(given = "Joe", surname = "Bloggs") %>% 
   add_indi(sex = "F") %>% 
   add_indi_names(given = "Jess", surname = "Bloggs") %>% 
   add_indi(sex = "F") %>% 
   add_indi_names(given = "Jessie", surname = "Bloggs") %>%
   add_famg(husband = "Joe", wife = "@I2@", children = "Jessie") %>% 
   add_famg_event_relationship(event_date = date_calendar(year = 1969, month = 1, day = 30),
                                 place_name = "Another place") %>% 
   tidyged.internals::remove_dates_for_tests() %>% 
   df_famg(), "json2")
})


test_that("Function df_media() @ L202", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_media(file_reference = "ref1", format = "WAV", source_media = "audio", title = "sounds") %>% 
   add_media(file_reference = "ref2", format = "JPEG", source_media = "photo", title = "photo1") %>% 
   add_media(file_reference = "ref3", format = "PNG", source_media = "photo", title = "photo2") %>% 
   tidyged.internals::remove_dates_for_tests() %>% 
   df_media(), "json2")
})


test_that("Function df_sour() @ L229", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_sour(originator = "author1", title = "book1") %>% 
   add_sour(originator = "author2", title = "book2") %>% 
   add_sour(originator = "author3", title = "book3") %>% 
   tidyged.internals::remove_dates_for_tests() %>% 
   df_sour(), "json2")
})


test_that("Function df_repo() @ L252", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_repo(name = "repo1", city = "Brighton", state = "E. Sussex", country = "UK") %>% 
   add_repo(name = "repo2", city = "Orlando", state = "Florida", country = "USA") %>% 
   add_repo(name = "repo3", city = "Yokohama", country = "Japan") %>% 
   tidyged.internals::remove_dates_for_tests() %>% 
   df_repo(), "json2")
})


test_that("Function df_note() @ L279", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_note(text = "This is a note", user_reference_number = 1234) %>% 
   add_note(text = "This is also a note", user_reference_number = 5678) %>% 
   add_note(text = "This may be a note too", user_reference_number = 987643) %>% 
   tidyged.internals::remove_dates_for_tests() %>% 
   df_note(), "json2")
})

