# Generated by roxytest: Do not edit by hand!


test_that("Function add_individual_names_var() @ L109", {
  expect_snapshot_value(
                 gedcom(subm("Me")) %>% 
                 add_individual() %>% 
                 add_individual_names("Joe /Bloggs/") %>% 
                 add_individual_names_var("Joe Bloggs", "JB", nickname = "JB", type = "tests", 
                                           phonetic_variation = FALSE) %>% 
                 remove_dates_for_tests(), "json2")
})


test_that("Function remove_individual_name() @ L208", {
  expect_equal(gedcom(subm()) %>% 
                 add_individual(),
               gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual_names("Joe Bloggs", given = "Joe", surname = "Bloggs") %>% 
                 remove_individual_name("Joe Bloggs"))
})


test_that("Function remove_individual_name_var() @ L238", {
  expect_equal(gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual_names("Joe Bloggs", given = "Joe", surname = "Bloggs"),
               gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual_names("Joe Bloggs", given = "Joe", surname = "Bloggs") %>% 
                 add_individual_names_var("Joe Bloggs", "Jo Blogs", "spelling error") %>% 
                 remove_individual_name_var("Jo Blogs"))
})

