# Generated by roxytest: Do not edit by hand!


test_that("Function remove_famg() @ L133", {
  expect_equal(gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi() %>% 
                 null_active_record(),
               gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi() %>% 
                 add_famg(husband = "@I1@", wife = "@I2@") %>% 
                 remove_famg())
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi() %>% 
                 add_famg(husband = "@I1@", wife = "@I2@") %>% 
                 remove_famg(remove_individuals = TRUE))
})

