# Generated by roxytest: Do not edit by hand!


test_that("Function place() @ L30", {
  expect_equal(place(), tibble::tibble())
  expect_snapshot_value(place("A place"), "json2")
})


test_that("Function address() @ L78", {
  expect_equal(address(), tibble::tibble())
  expect_snapshot_value(address("A place"), "json2")
})

