# Generated by roxytest: Do not edit by hand!


test_that("Function summary.tidygedcom() @ L56", {
  expect_snapshot_value(
                 gedcom(subm("Me"), gedcom_description = "descrip", language = "English",
                        gedcom_copyright = "copyright statement") %>% 
                  summary(), "json2")
})


test_that("Function str.tidygedcom() @ L100", {
  expect_snapshot_value(
   gedcom(subm("Me")) %>% 
    add_individual() %>% 
    add_individual() %>% 
    add_individual() %>% 
    add_family_group() %>% 
    add_family_group() %>% 
    add_multimedia("ref1", "AAC") %>% 
    add_multimedia("ref1", "AAC") %>% 
    add_source() %>% 
    add_repository("repo") %>% 
    add_note("note1") %>% 
    add_note("note2") %>% 
    str(), "json2")
})


test_that("Function df_individuals() @ L146", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_individual(sex = "M") %>% 
   add_individual_names("Joe Bloggs") %>% 
   add_individual_event_birth(event_date = date_value(start_year = 1950, start_month = 5, start_day = 7),
                              place_name = "Somewhere") %>% 
   add_individual_event_death(event_date = date_value(start_year = 2000, start_month = 12, start_day = 1),
                              place_name = "Somewhere else") %>% 
   add_individual(sex = "F") %>% 
   add_individual_names("Jess Bloggs") %>% 
   add_individual_event_birth(event_date = date_value(start_year = 1948, start_month = 1, start_day = 15),
                              place_name = "Somewhere") %>% 
   add_individual(sex = "F") %>% 
   add_individual_names("Jessie Bloggs") %>% 
   add_individual_event_birth(event_date = date_value(start_year = 1970, about = TRUE),
                              place_name = "Elsewhere") %>%
   add_family_group(husband = "Joe", wife = "Jess Bloggs", children = "Jessie") %>% 
   add_family_event_relationship(event_date = date_value(start_year = 1969, start_month = 1, start_day = 30),
                                 place_name = "Another place") %>% 
   remove_dates_for_tests() %>% 
   df_individuals(), "json2")
})


test_that("Function df_families() @ L204", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_individual(sex = "M") %>% 
   add_individual_names("Joe Bloggs") %>% 
   add_individual(sex = "F") %>% 
   add_individual_names("Jess Bloggs") %>% 
   add_individual(sex = "F") %>% 
   add_individual_names("Jessie Bloggs") %>%
   add_family_group(husband = "Joe", wife = "Jess Bloggs", children = "Jessie") %>% 
   add_family_event_relationship(event_date = date_value(start_year = 1969, start_month = 1, start_day = 30),
                                 place_name = "Another place") %>% 
   remove_dates_for_tests() %>% 
   df_families(), "json2")
})


test_that("Function df_multimedia() @ L238", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_multimedia(file_reference = "ref1", format = "WAV", source_media = "audio", title = "sounds") %>% 
   add_multimedia(file_reference = "ref2", format = "JPEG", source_media = "photo", title = "photo1") %>% 
   add_multimedia(file_reference = "ref3", format = "PNG", source_media = "photo", title = "photo2") %>% 
   remove_dates_for_tests() %>% 
   df_multimedia(), "json2")
})


test_that("Function df_sources() @ L265", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_source(originator = "author1", title = "book1") %>% 
   add_source(originator = "author2", title = "book2") %>% 
   add_source(originator = "author3", title = "book3") %>% 
   remove_dates_for_tests() %>% 
   df_sources(), "json2")
})


test_that("Function df_repositories() @ L288", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_repository(name = "repo1", city = "Brighton", state = "E. Sussex", country = "UK") %>% 
   add_repository(name = "repo2", city = "Orlando", state = "Florida", country = "USA") %>% 
   add_repository(name = "repo3", city = "Yokohama", country = "Japan") %>% 
   remove_dates_for_tests() %>% 
   df_repositories(), "json2")
})


test_that("Function df_notes() @ L315", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_note(text = "This is a note", user_reference_number = 1234) %>% 
   add_note(text = "This is also a note", user_reference_number = 5678) %>% 
   add_note(text = "This may be a note too", user_reference_number = 987643) %>% 
   remove_dates_for_tests() %>% 
   df_notes(), "json2")
})

