# Generated by roxytest: Do not edit by hand!

# File R/find_xref.R: @tests

test_that("Function find_xref() @ L39", {
  expect_error(find_xref(sample555, character()))
  expect_error(find_xref(sample555, c(INDI.NAME = "test"), mode = "foo"))
  expect_error(find_xref(sample555, letters[1:5]))
  expect_error(find_xref(sample555, c(a = "das", "sd", b = "r42")))
  expect_error(find_xref(sample555, c(INDI.SEX = "L")))
  expect_error(find_xref(sample555, c(INDI.NAME.SURN = "Williams")))
  expect_equal(find_xref(sample555, c(FAM.MARR.DATE = "1859")), "@F1@")
  expect_equal(find_xref(sample555, c(INDI.SEX = "M", INDI.NAME.SURN = "Williams", INDI.BIRT.PLAC = "Falls")), "@I3@")
})

