# Generated by roxytest: Do not edit by hand!

context("File R/edit_individual_attributes.R: @tests")

test_that("Function add_individual_attribute() @ L26", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
                         add_individual(sex = "M") %>% 
                         add_individual_attribute_occupation(attribute_descriptor = "Jedi",
                                                             update_date_changed = FALSE) %>% 
                         remove_dates_for_tests(), "json2")
})

