# Generated by roxytest: Do not edit by hand!

context("File R/primitives.R: @tests")

test_that("Function validate_date() @ L42", {
  expect_error(validate_date(2005, day1 = 15))
  expect_error(validate_date(2005, 10, 15, month2 = 4))
  expect_error(validate_date(2005, 10, 15, day2 = 15))
  expect_error(validate_date(2005, 10, 15, 2015, day2 = 15))
  expect_error(validate_date(2005, 13))
  expect_error(validate_date(2005, 10, 32))
  expect_error(validate_date(2005, -1, 6))
  expect_error(validate_date(2005, 6, 15, 2005, 0, 20))
  expect_error(validate_date(2005, 5, 18, 2006, 2, 29))
  expect_error(validate_date(2005, 3, year2 = 2005, month2 = 2))
  expect_error(validate_date(2005, year2 = 2004))
})

