# Generated by roxytest: Do not edit by hand!


test_that("Function add_indi_association() @ L23", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
                          add_indi("Joe /Bloggs/") %>% 
                          add_indi("Jimmy /Bloggs/") %>% 
                          add_indi_association(associated_with = "Joe", association = "Friend") %>% 
                          remove_dates_for_tests(), "json2")
})

