# Generated by roxytest: Do not edit by hand!


test_that("Function remove_family_group() @ L145", {
  expect_equal(gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual() %>% 
                 null_active_record(),
               gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual() %>% 
                 add_family_group(husband = "@I1@", wife = "@I2@") %>% 
                 remove_family_group())
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual() %>% 
                 add_family_group(husband = "@I1@", wife = "@I2@") %>% 
                 remove_family_group(remove_individuals = TRUE))
})

