# Generated by roxytest: Do not edit by hand!


test_that("Function add_famg_event() @ L29", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_indi("Joe Bloggs", sex = "M") %>% 
   add_indi("Jess Bloggs", sex = "F") %>% 
   add_indi("Jessie Bloggs", sex = "F") %>% 
   add_famg(husband = "Joe", wife = "Jess Bloggs", children = "Jessie") %>% 
   add_famg_event(event_type = "MARR", 
                    event_date = date_calendar(year = 1969, month = 1, day = 30),
                    place_name = "Another place") %>% 
   remove_dates_for_tests(), "json2")
})

