# Generated by roxytest: Do not edit by hand!

context("File R/records.R: @tests")

test_that("Function GEDCOM_HEADER() @ L28", {
  expect_error(GEDCOM_HEADER("ANSEL"))
  expect_snapshot_value(GEDCOM_HEADER(), "json2")
  expect_snapshot_value(GEDCOM_HEADER(
          header_extension = LINEAGE_LINKED_HEADER_EXTENSION(language_of_text = "English")), "json2")
})


test_that("Function FAMILY_GROUP_RECORD() @ L74", {
  expect_error(FAMILY_GROUP_RECORD("@F1@", user_reference_number = 123:125, user_reference_type = letters[1:2]))
  expect_equal(FAMILY_GROUP_RECORD("@F1@"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "@F1@", "FAM",                      "",
                               1, "@F1@", "CHAN",                     "",
                               2, "@F1@", "DATE", toupper(format(Sys.Date(), "%d %b %Y"))
               ))
})


test_that("Function INDIVIDUAL_RECORD() @ L160", {
  expect_error(INDIVIDUAL_RECORD("@I1@", user_reference_number = 123:125, user_reference_type = letters[1:2]))
  expect_equal(INDIVIDUAL_RECORD("@I1@"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "@I1@", "INDI",                      "",
                               1, "@I1@", "CHAN",                      "",
                               2, "@I1@", "DATE", toupper(format(Sys.Date(), "%d %b %Y"))
               ))
})


test_that("Function MULTIMEDIA_RECORD() @ L238", {
  expect_error(MULTIMEDIA_RECORD("@M1@", "file_ref", "JPG",
                                 user_reference_number = 123:125, user_reference_type = letters[1:2]))
  expect_equal(MULTIMEDIA_RECORD("@M1@", "file_ref", "JPG"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "@M1@", "OBJE",                      "",
                               1, "@M1@", "FILE",              "file_ref",
                               2, "@M1@", "FORM",                   "JPG",
                               1, "@M1@", "CHAN",                      "",
                               2, "@M1@", "DATE", toupper(format(Sys.Date(), "%d %b %Y"))
               ))
})


test_that("Function NOTE_RECORD() @ L326", {
  expect_error(NOTE_RECORD("@N1@", "This is a note",
                                 user_reference_number = 123:125, user_reference_type = letters[1:2]))
  expect_equal(NOTE_RECORD("@N1@", "This is a note"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "@N1@", "NOTE",        "This is a note",
                               1, "@N1@", "CHAN",                      "",
                               2, "@N1@", "DATE", toupper(format(Sys.Date(), "%d %b %Y"))
               ))
})


test_that("Function REPOSITORY_RECORD() @ L385", {
  expect_error(REPOSITORY_RECORD("@R1@", "Repo name",
                                 user_reference_number = 123:125, user_reference_type = letters[1:2]))
  expect_equal(REPOSITORY_RECORD("@R1@", "Repo name"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "@R1@", "REPO",                      "",
                               1, "@R1@", "NAME",             "Repo name",
                               1, "@R1@", "CHAN",                      "",
                               2, "@R1@", "DATE", toupper(format(Sys.Date(), "%d %b %Y"))
               ))
})


test_that("Function SOURCE_RECORD() @ L447", {
  expect_error(SOURCE_RECORD("@S1@",
                             user_reference_number = 123:125, user_reference_type = letters[1:2]))
  expect_equal(SOURCE_RECORD("@S1@"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "@S1@", "SOUR",                      "",
                               1, "@S1@", "CHAN",                      "",
                               2, "@S1@", "DATE", toupper(format(Sys.Date(), "%d %b %Y"))
               ))
})


test_that("Function SUBMITTER_RECORD() @ L547", {
  expect_equal(SUBMITTER_RECORD("@S1@", "Joe Bloggs"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "@S1@", "SUBM",                      "",
                               1, "@S1@", "NAME",            "Joe Bloggs",
                               1, "@S1@", "CHAN",                      "",
                               2, "@S1@", "DATE", toupper(format(Sys.Date(), "%d %b %Y"))
               ))
})


test_that("Function FOOTER_SECTION() @ L584", {
  expect_equal(FOOTER_SECTION(),
               tibble::tribble(~level,  ~record,   ~tag, ~value,
                               0, "TR", "TRLR",     ""
               ))
})

