# Generated by roxytest: Do not edit by hand!

# File R/describe.R: @tests

test_that("Function describe_records() @ L15", {
  expect_snapshot_value(describe_records(sample555, sample555$record, TRUE), "json2")
  expect_snapshot_value(describe_records(sample555, sample555$record), "json2")
})

