# Generated by roxytest: Do not edit by hand!

# File R/multimedia.R: @tests

test_that("Function remove_media() @ L69", {
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% 
               add_media("test", "BMP") %>% 
               remove_media())
})

