# Generated by roxytest: Do not edit by hand!


test_that("Function add_indi_event() @ L79", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
                         add_indi(sex = "M") %>% 
                         add_indi_event(event_type = "CHR",
                                        event_date = date_calendar(year = 1956),
                                        age_at_event = "1y",
                                        local_address_lines = c("line1","line2","line3","line4"),
                                        place_name = "There",
                                        place_notes = "Place note") %>% 
                         tidyged.internals::remove_dates_for_tests(), "json2")
})

