# Generated by roxytest: Do not edit by hand!


test_that("Function remove_repository() @ L91", {
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% add_repository("text") %>% remove_repository())
})

