# Generated by roxytest: Do not edit by hand!


test_that("Function get_spouses() @ L16", {
  expect_equal(get_spouses(sample555, "@I1@"), "@I2@")
  expect_equal(get_spouses(sample555, "@I2@"), "@I1@")
  expect_equal(get_spouses(sample555, "@I3@"), character(0))
})


test_that("Function get_children() @ L48", {
  expect_error(get_children(sample555, "@I4@"))
  expect_equal(get_children(sample555, "@I1@"), "@I3@")
  expect_equal(get_children(sample555, "@I2@"), "@I3@")
})


test_that("Function get_parents() @ L77", {
  expect_equal(get_parents(sample555, "@I3@"), c("@I1@", "@I2@"))
})


test_that("Function get_families_as_spouse() @ L106", {
  expect_equal(get_families_as_spouse(sample555, "@I1@"), c("@F1@", "@F2@"))
  expect_equal(get_families_as_spouse(sample555, "@I2@"), "@F1@")
})


test_that("Function get_families_as_child() @ L124", {
  expect_equal(get_families_as_child(sample555, "@I3@"), c("@F1@", "@F2@"))
})


test_that("Function xrefs_indi() @ L208", {
  expect_equal(xrefs_indi(sample555), paste0("@I", 1:3, "@"))
})


test_that("Function xrefs_famg() @ L214", {
  expect_equal(xrefs_famg(sample555), paste0("@F", 1:2, "@"))
})


test_that("Function xrefs_subm() @ L220", {
  expect_equal(xrefs_subm(sample555), paste0("@U", 1, "@"))
})


test_that("Function xrefs_sour() @ L226", {
  expect_equal(xrefs_sour(sample555), paste0("@S", 1, "@"))
})

