# Generated by roxytest: Do not edit by hand!

context("File R/interrogate.R: @tests")

test_that("Function df_individuals() @ L126", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_individual(sex = "M") %>% 
   add_individual_names("Joe Bloggs") %>% 
   add_individual_event_birth(event_date = date_value(start_year = 1950, start_month = 5, start_day = 7),
                              place_name = "Somewhere") %>% 
   add_individual_event_death(event_date = date_value(start_year = 2000, start_month = 12, start_day = 1),
                              place_name = "Somewhere else") %>% 
   add_individual(sex = "F") %>% 
   add_individual_names("Jess Bloggs") %>% 
   add_individual_event_birth(event_date = date_value(start_year = 1948, start_month = 1, start_day = 15),
                              place_name = "Somewhere") %>% 
   add_individual(sex = "F") %>% 
   add_individual_names("Jessie Bloggs") %>% 
   add_individual_event_birth(event_date = date_value(start_year = 1970, about = TRUE),
                              place_name = "Elsewhere") %>%
   add_family_group(husband = "Joe", wife = "Jess Bloggs", children = "Jessie") %>% 
   add_family_event_marriage(event_date = date_value(start_year = 1969, start_month = 1, start_day = 30),
                             place_name = "Another place") %>% 
   remove_dates_for_tests() %>% 
   df_individuals(), "json2")
})


test_that("Function df_families() @ L184", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
   add_individual(sex = "M") %>% 
   add_individual_names("Joe Bloggs") %>% 
   add_individual(sex = "F") %>% 
   add_individual_names("Jess Bloggs") %>% 
   add_individual(sex = "F") %>% 
   add_individual_names("Jessie Bloggs") %>%
   add_family_group(husband = "Joe", wife = "Jess Bloggs", children = "Jessie") %>% 
   add_family_event_marriage(event_date = date_value(start_year = 1969, start_month = 1, start_day = 30),
                             place_name = "Another place") %>% 
   remove_dates_for_tests() %>% 
   df_families(), "json2")
})

