# Generated by roxytest: Do not edit by hand!


test_that("Function add_individual_association() @ L23", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
                          add_individual("Joe /Bloggs/") %>% 
                          add_individual("Jimmy /Bloggs/") %>% 
                          add_individual_association(associated_with = "Joe", association = "Friend") %>% 
                          remove_dates_for_tests(), "json2")
})

