# Generated by roxytest: Do not edit by hand!


test_that("Function read_gedcom() @ L27", {
  expect_error(read_gedcom("my_family.txt"))
  expect_snapshot_value(
      read_gedcom(system.file("extdata", "555SAMPLE.GED", package = "tidyged")), 
      "json2")
  expect_snapshot_value(
      read_gedcom(system.file("extdata", "555SAMPLE16BE.GED", package = "tidyged")), 
      "json2")
  expect_snapshot_value(
      read_gedcom(system.file("extdata", "555SAMPLE16LE.GED", package = "tidyged")), 
      "json2")
})


test_that("Function read_gedcom_encoding() @ L76", {
  expect_equal(
    read_gedcom_encoding(system.file("extdata", "555SAMPLE.GED", package = "tidyged")), 
    "UTF-8")
  expect_equal(
    read_gedcom_encoding(system.file("extdata", "555SAMPLE16BE.GED", package = "tidyged")), 
    "UTF-16BE")
  expect_equal(
    read_gedcom_encoding(system.file("extdata", "555SAMPLE16LE.GED", package = "tidyged")), 
    "UTF-16LE")
})


test_that("Function check_line_lengths() @ L101", {
  expect_error(check_line_lengths(c("the", "quick", "brown", "fox"), 4))
  expect_equal(check_line_lengths(c("the", "quick", "brown", "fox"), 5),
                                  c("the", "quick", "brown", "fox"))
})


test_that("Function write_gedcom() @ L157", {
  expect_warning(write_gedcom(gedcom(), "my_family.txt") %>% file.remove("my_family.txt"))
})


test_that("Function update_header_with_filename() @ L198", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
                          update_header_with_filename("my_file.ged") %>% 
                          remove_dates_for_tests(), "json2")
  expect_snapshot_value(read_gedcom(system.file("extdata", "555SAMPLE.GED", package = "tidyged")) %>% 
                          update_header_with_filename("my_file.ged") %>% 
                          remove_dates_for_tests(), "json2")
})


test_that("Function split_gedcom_values() @ L230", {
  expect_snapshot_value(
                  gedcom(subm("Me")) %>% 
                    add_source(title = paste(rep("a", 4095), collapse = "")) %>%
                    remove_dates_for_tests() %>% 
                    split_gedcom_values(248), "json2")
})

