# Generated by roxytest: Do not edit by hand!


test_that("Function construct_full_name() @ L29", {
  expect_error(construct_full_name(surname_prefix = "de la"))
  expect_equal(construct_full_name(prefix = "Lt. Cdr."), "Lt. Cdr.")
  expect_equal(construct_full_name(given = "Joe"), "Joe")
  expect_equal(construct_full_name(given = "Joe,Adam"), "Joe Adam")
  expect_equal(construct_full_name(given = "Joey,Joe, Joe"), "Joey Joe Joe")
  expect_equal(construct_full_name(nickname = "Nobby"), "'Nobby'")
  expect_equal(construct_full_name(surname = "Bloggs"), "/Bloggs/")
  expect_equal(construct_full_name(suffix = "Jr."), "Jr.")
  expect_equal(construct_full_name(suffix = "Jr.,Esq."), "Jr. Esq.")
  expect_equal(construct_full_name(prefix = "Lt. Cdr.", given = "Joe,Adam", nickname = "Nobby", 
                                   surname_prefix = "de la", surname = "Bloggs",
                                   suffix = "Jr., Esq."),
               "Lt. Cdr. Joe Adam 'Nobby' de la /Bloggs/ Jr. Esq.")
})


test_that("Function remove_records() @ L155", {
  expect_snapshot_value(remove_records(sample555, c("@I1@","@I2@")), "json2")
  expect_snapshot_value(remove_records(sample555, c("@S1@","@R1@")), "json2")
  expect_snapshot_value(remove_records(sample555, c("@F1@","@I3@")), "json2")
})

