# Generated by roxytest: Do not edit by hand!

# File R/identify.R: @tests

test_that("Function get_families_as_partner() @ L15", {
  expect_equal(get_families_as_partner(sample555, "@I1@"), c("@F1@", "@F2@"))
  expect_equal(get_families_as_partner(sample555, "@I2@"), "@F1@")
})


test_that("Function get_families_as_child() @ L37", {
  expect_equal(get_families_as_child(sample555, "@I3@"), c("@F1@", "@F2@"))
})


test_that("Function get_partners() @ L86", {
  expect_equal(get_partners(sample555, "@I1@"), "@I2@")
  expect_equal(get_partners(sample555, "@I2@", TRUE), "Robert Eugene Williams")
  expect_equal(get_partners(sample555, "@I3@"), character(0))
})


test_that("Function get_children() @ L121", {
  expect_error(get_children(sample555, "@I4@"))
  expect_equal(get_children(sample555, "@I1@"), "@I3@")
  expect_equal(get_children(sample555, "@I2@", TRUE), "Joe Williams")
})


test_that("Function get_parents() @ L155", {
  expect_equal(get_parents(sample555, "@I3@"), c("@I1@", "@I2@"))
  expect_equal(get_parents(sample555, "@I3@", TRUE), c("Robert Eugene Williams", "Mary Ann Wilson"))
})


test_that("Function get_supporting_records() @ L272", {
  expect_equal(get_supporting_records(sample555, "@I1@"), c("@S1@", "@R1@"))
})


test_that("Function get_descendants() @ L321", {
  expect_equal(get_descendants(sample555, "@I1@"), "@I3@")
  expect_equal(get_descendants(sample555, "@I1@", TRUE), c("@I1@","@I3@"))
  expect_equal(get_descendants(sample555, "@I1@", TRUE, TRUE), c("@I2@","@I1@","@I3@"))
  expect_equal(get_descendants(sample555, "@I1@", TRUE, TRUE, TRUE), c("@F1@","@F2@","@I2@","@I1@","@I3@"))
})


test_that("Function xrefs_indi() @ L452", {
  expect_equal(xrefs_indi(sample555), paste0("@I", 1:3, "@"))
})


test_that("Function xrefs_famg() @ L458", {
  expect_equal(xrefs_famg(sample555), paste0("@F", 1:2, "@"))
})


test_that("Function xrefs_subm() @ L464", {
  expect_equal(xrefs_subm(sample555), paste0("@U", 1, "@"))
})


test_that("Function xrefs_sour() @ L470", {
  expect_equal(xrefs_sour(sample555), paste0("@S", 1, "@"))
})

