# Generated by roxytest: Do not edit by hand!


test_that("Function add_individual_event() @ L77", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
                         add_individual(sex = "M") %>% 
                         add_individual_event(event_type = "CHR",
                                              event_date = date_value(start_year = 1956),
                                              age_at_event = "1y",
                                               local_address_lines = c("line1","line2","line3","line4"),
                                               place_name = "There",
                                               place_notes = "Place note") %>% 
                         remove_dates_for_tests(), "json2")
})

