# Generated by roxytest: Do not edit by hand!


test_that("Function remove_media() @ L64", {
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% 
               add_media("test", "BMP") %>% 
               remove_media())
})

