# Generated by roxytest: Do not edit by hand!

context("File R/helpers_dates.R: @tests")

test_that("Function date_exact_pattern() @ L41", {
  expect_equal(grepl(date_exact_pattern(), "14 JAN 2005"), TRUE)
  expect_equal(grepl(date_exact_pattern(), "14 JAM 2005"), FALSE)
  expect_equal(grepl(date_exact_pattern(), "JAN 2005"), FALSE)
  expect_equal(grepl(date_exact_pattern(), "14 JAN 2005/06"), TRUE)
  expect_equal(grepl(date_exact_pattern(), "5 JUL 2005"), TRUE)
  expect_equal(grepl(date_exact_pattern(), "8 NOV 1956/57"), TRUE)
  expect_equal(grepl(date_exact_pattern(), "2005"), FALSE)
  expect_equal(grepl(date_exact_pattern(), "15 NOV 125"), FALSE)
  expect_equal(grepl(date_exact_pattern(), "JAN 1901/58"), FALSE)
  expect_equal(grepl(date_exact_pattern(), "5 JUL 2005 "), FALSE)
  expect_equal(grepl(date_exact_pattern(), " 5 JUL 2005"), FALSE)
})


test_that("Function date_pattern() @ L64", {
  expect_equal(grepl(date_pattern(), "14 JAN 2005"), TRUE)
  expect_equal(grepl(date_pattern(), "14 JAM 2005"), FALSE)
  expect_equal(grepl(date_pattern(), "JAN 2005"), TRUE)
  expect_equal(grepl(date_pattern(), "14 JAN 2005/06"), TRUE)
  expect_equal(grepl(date_pattern(), "5 JUL 2005"), TRUE)
  expect_equal(grepl(date_pattern(), "8 NOV 1956/57"), TRUE)
  expect_equal(grepl(date_pattern(), "2005"), TRUE)
  expect_equal(grepl(date_pattern(), "15 NOV 125"), FALSE)
  expect_equal(grepl(date_pattern(), "JAN 1901/58"), TRUE)
  expect_equal(grepl(date_pattern(), "5 JUL 2005 "), FALSE)
  expect_equal(grepl(date_pattern(), " 5 JUL 2005"), FALSE)
})


test_that("Function date_period_pattern() @ L94", {
  expect_equal(grepl(date_period_pattern(), "FROM 14 JAN 2005"), TRUE)
  expect_equal(grepl(date_period_pattern(), "TO 14 JAM 2005"), FALSE)
  expect_equal(grepl(date_period_pattern(), "FROM JAN 2005"), TRUE)
  expect_equal(grepl(date_period_pattern(), "FROM 14 JAN 2005/06 TO 2007"), TRUE)
  expect_equal(grepl(date_period_pattern(), "TO 5 JUL 2005"), TRUE)
  expect_equal(grepl(date_period_pattern(), "TO  8 NOV 1956/57"), FALSE)
  expect_equal(grepl(date_period_pattern(), "FROM 2005"), TRUE)
  expect_equal(grepl(date_period_pattern(), "FROM 15 NOV 125"), FALSE)
  expect_equal(grepl(date_period_pattern(), " TO JAN 1901/58"), FALSE)
  expect_equal(grepl(date_period_pattern(), "FROM 5 JUL 2005 "), FALSE)
  expect_equal(grepl(date_period_pattern(), " TO 5 JUL 2005"), FALSE)
})


test_that("Function date_range_pattern() @ L125", {
  expect_equal(grepl(date_range_pattern(), "BEF 14 JAN 2005"), TRUE)
  expect_equal(grepl(date_range_pattern(), "AFT 14 JAM 2005"), FALSE)
  expect_equal(grepl(date_range_pattern(), "BEF JAN 2005"), TRUE)
  expect_equal(grepl(date_range_pattern(), "BET 14 JAN 2005/06 AND 2007"), TRUE)
  expect_equal(grepl(date_range_pattern(), "AFT 5 JUL 2005"), TRUE)
  expect_equal(grepl(date_range_pattern(), "AFT  8 NOV 1956/57"), FALSE)
  expect_equal(grepl(date_range_pattern(), "BEF 2005"), TRUE)
  expect_equal(grepl(date_range_pattern(), "BEF 15 NOV 125"), FALSE)
  expect_equal(grepl(date_range_pattern(), " AFT JAN 1901/58"), FALSE)
  expect_equal(grepl(date_range_pattern(), "BEF 5 JUL 2005 "), FALSE)
  expect_equal(grepl(date_range_pattern(), " AFT 5 JUL 2005"), FALSE)
})


test_that("Function date_approximated_pattern() @ L156", {
  expect_equal(grepl(date_approximated_pattern(), "ABT 14 JAN 2005"), TRUE)
  expect_equal(grepl(date_approximated_pattern(), "CAL 14 JAM 2005"), FALSE)
  expect_equal(grepl(date_approximated_pattern(), "EST JAN 2005"), TRUE)
  expect_equal(grepl(date_approximated_pattern(), "ABT 14 JAN 2005/06 AND 2007"), FALSE)
  expect_equal(grepl(date_approximated_pattern(), "EST 5 JUL 2005"), TRUE)
  expect_equal(grepl(date_approximated_pattern(), "CAL  8 NOV 1956/57"), FALSE)
  expect_equal(grepl(date_approximated_pattern(), "ABT 2005"), TRUE)
  expect_equal(grepl(date_approximated_pattern(), "CAL 15 NOV 125"), FALSE)
  expect_equal(grepl(date_approximated_pattern(), " EST JAN 1901/58"), FALSE)
  expect_equal(grepl(date_approximated_pattern(), "CAL 5 JUL 2005 "), FALSE)
  expect_equal(grepl(date_approximated_pattern(), " CAL 5 JUL 2005"), FALSE)
})


test_that("Function date_value_pattern() @ L195", {
  expect_equal(grepl(date_value_pattern(), "14 JAN 2005"), TRUE)
  expect_equal(grepl(date_value_pattern(), "MAR 1901"), TRUE)
  expect_equal(grepl(date_value_pattern(), "2010"), TRUE)
  expect_equal(grepl(date_value_pattern(), "FROM 14 FEB 2005"), TRUE)
  expect_equal(grepl(date_value_pattern(), "TO JAN 2005"), TRUE)
  expect_equal(grepl(date_value_pattern(), "FROM 14 JAN 2005/06 TO 2007"), TRUE)
  expect_equal(grepl(date_value_pattern(), "BEF 5 JUL 2005"), TRUE)
  expect_equal(grepl(date_value_pattern(), "AFT 8 NOV 1956/57"), TRUE)
  expect_equal(grepl(date_value_pattern(), "BET 2005 AND MAR 2008"), TRUE)
  expect_equal(grepl(date_value_pattern(), "CAL 15 NOV 1925"), TRUE)
  expect_equal(grepl(date_value_pattern(), "EST JAN 1901/58"), TRUE)
  expect_equal(grepl(date_value_pattern(), "ABT 5 JUL 2005"), TRUE)
  expect_equal(grepl(date_value_pattern(), "14 JAN 205"), FALSE)
  expect_equal(grepl(date_value_pattern(), "MAR 1901 "), FALSE)
  expect_equal(grepl(date_value_pattern(), " 2010"), FALSE)
  expect_equal(grepl(date_value_pattern(), "FROM 14 FEBR 2005"), FALSE)
  expect_equal(grepl(date_value_pattern(), "TO  JAN 2005"), FALSE)
  expect_equal(grepl(date_value_pattern(), "FROM 14 JAN 2005/06 AND 2007"), FALSE)
  expect_equal(grepl(date_value_pattern(), "BEF 5 JUL 2005 "), FALSE)
  expect_equal(grepl(date_value_pattern(), "AFT 8 NOV 1956/1957"), FALSE)
  expect_equal(grepl(date_value_pattern(), "BET 2005 TO MAR 2008"), FALSE)
  expect_equal(grepl(date_value_pattern(), "CAL 15 NOV 1925/"), FALSE)
  expect_equal(grepl(date_value_pattern(), "14TH JAN 1901/58"), FALSE)
  expect_equal(grepl(date_value_pattern(), "ABT 5  JUL 2005"), FALSE)
})


test_that("Function date_exact() @ L217", {
  expect_equal(date_exact(12), character())
  expect_equal(date_exact(12, 8), character())
  expect_equal(date_exact(12, 8, 2005), "12 AUG 2005")
})


test_that("Function date_value() @ L264", {
  expect_equal(date_value(2005), "2005")
  expect_equal(date_value(2005, 1), "JAN 2005")
  expect_equal(date_value(2005, 1, 14), "14 JAN 2005")
  expect_equal(date_value(2005, after = TRUE), "AFT 2005")
  expect_equal(date_value(2010, before = TRUE), "BEF 2010")
  expect_equal(date_value(2005, 10, 14, before = TRUE), "BEF 14 OCT 2005")
  expect_equal(date_value(1900, 6, 30, from = TRUE), "FROM 30 JUN 1900")
  expect_equal(date_value(2000, 1, 1, to = TRUE), "TO 1 JAN 2000")
  expect_equal(date_value(2005, 1, 14, 2006, 7, 9, from = TRUE, to = TRUE), "FROM 14 JAN 2005 TO 9 JUL 2006")
  expect_equal(date_value(2005, 1, 14, 2006, 7, 9, between = TRUE), "BET 14 JAN 2005 AND 9 JUL 2006")
  expect_equal(date_value(2005, 1, 14, calc = TRUE), "CAL 14 JAN 2005")
  expect_equal(date_value(2005, est = TRUE), "EST 2005")
  expect_equal(date_value(2005, 1, about = TRUE), "ABT JAN 2005")
})


test_that("Function date_period() @ L340", {
  expect_equal(date_period(2005), "FROM 2005")
  expect_equal(date_period(2005, 1), "FROM JAN 2005")
  expect_equal(date_period(2005, 1, 14), "FROM 14 JAN 2005")
  expect_equal(date_period(2005, to = TRUE), "TO 2005")
  expect_equal(date_period(2010, 6, to = TRUE), "TO JUN 2010")
  expect_equal(date_period(2005, 10, 14, 2008, 9), "FROM 14 OCT 2005 TO SEP 2008")
  expect_equal(date_period(1900, 6, 30, 1901), "FROM 30 JUN 1900 TO 1901")
})

