# Generated by roxytest: Do not edit by hand!

context("File R/edit_repository.R: @tests")

test_that("Function remove_repository() @ L87", {
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% add_repository("text") %>% remove_repository())
})

