# Generated by roxytest: Do not edit by hand!


test_that("Function add_indi_names_var() @ L114", {
  expect_snapshot_value(
                 gedcom(subm("Me")) %>% 
                 add_indi() %>% 
                 add_indi_names("Joe /Bloggs/") %>% 
                 add_indi_names_var("Joe Bloggs", "JB", nickname = "JB", type = "tests", 
                                           phonetic_variation = FALSE) %>% 
                 remove_dates_for_tests(), "json2")
})


test_that("Function remove_indi_name() @ L215", {
  expect_equal(gedcom(subm()) %>% 
                 add_indi(),
               gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi_names("Joe Bloggs", given = "Joe", surname = "Bloggs") %>% 
                 remove_indi_name("Joe Bloggs"))
})


test_that("Function remove_indi_name_var() @ L245", {
  expect_equal(gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi_names("Joe Bloggs", given = "Joe", surname = "Bloggs"),
               gedcom(subm()) %>% 
                 add_indi() %>% 
                 add_indi_names("Joe Bloggs", given = "Joe", surname = "Bloggs") %>% 
                 add_indi_names_var("Joe Bloggs", "Jo /Blogs/", "spelling error") %>% 
                 remove_indi_name_var("Jo /Blogs/"))
})

