# Generated by roxytest: Do not edit by hand!

context("File R/edit_source.R: @tests")

test_that("Function remove_source() @ L159", {
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% add_source(title = "text") %>% remove_source())
})

