# Generated by roxytest: Do not edit by hand!


test_that("Function describe_famg() @ L65", {
  expect_equal(gedcom() %>% add_famg() %>% describe_famg("@F1@"),
               "Family @F1@, headed by no individuals, and no children")
})

