# Generated by roxytest: Do not edit by hand!


test_that("Function remove_multimedia() @ L74", {
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% 
               add_multimedia("test", "BMP") %>% 
               remove_multimedia())
})

