# Generated by roxytest: Do not edit by hand!

context("File R/subrecords.R: @tests")

test_that("Function LINEAGE_LINKED_HEADER_EXTENSION() @ L73", {
  expect_error(HEADER_SECTION())
  expect_error(HEADER_SECTION("@1@"))
  expect_error(HEADER_SECTION("@1@", approved_system_id = "system"))
  expect_error(HEADER_SECTION("@1@", approved_system_id = "system", character_set = "red"))
  
  expect_equal(HEADER_SECTION("@1@", approved_system_id = "system", character_set = "UTF-8",
                              xref_subn = "@2@", system_version_number = "1.0", name_of_product = "R",
                              copyright_gedcom_file = "Do not copy", language = "English",
                              gedcom_content_description = "This is a gedcom file"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "HD", "HEAD",                      "",
                               1, "HD", "SOUR",                "system",
                               2, "HD", "VERS",                   "1.0",
                               2, "HD", "NAME",                     "R",
                               1, "HD", "SUBM",                   "@1@",
                               1, "HD", "SUBN",                   "@2@",
                               1, "HD", "COPR",           "Do not copy",
                               1, "HD", "GEDC",                      "",
                               2, "HD", "VERS",                 "5.5.1",
                               2, "HD", "FORM",        "Lineage-Linked",
                               1, "HD", "CHAR",                 "UTF-8",
                               1, "HD", "LANG",               "English",
                               1, "HD", "NOTE", "This is a gedcom file"
               ))
  
  expect_equal(HEADER_SECTION("@1@", approved_system_id = "system", character_set = "UTF-8",
                              xref_subn = "@2@", system_version_number = "1.0", name_of_product = "R",
                              name_of_business = "RStudio", business_address = ADDRESS_STRUCTURE(c("Street", "City", "State")),
                              name_of_source_data = "Source text", publication_date_source_data = date_exact(5, 9, 2005),
                              copyright_source_data = "Source is protected", receiving_system_name = "Windows",
                              transmission_date = date_exact(15, 10, 2020), file_name = "test.ged",
                              copyright_gedcom_file = "Do not copy", language = "English", place_hierarchy = "here",
                              gedcom_content_description = "This is a gedcom file"),
               tibble::tribble(~level,  ~record,   ~tag,                  ~value,
                               0, "HD", "HEAD",                      "",
                               1, "HD", "SOUR",                "system",
                               2, "HD", "VERS",                   "1.0",
                               2, "HD", "NAME",                     "R",
                               2, "HD", "CORP",               "RStudio",
                               3, "HD", "ADDR",                "Street",
                               4, "HD", "CONT",                  "City",
                               4, "HD", "CONT",                 "State",
                               4, "HD", "ADR1",                  "City",
                               4, "HD", "ADR2",                 "State",
                               2, "HD", "DATA",           "Source text",
                               3, "HD", "DATE",            "5 SEP 2005",
                               3, "HD", "COPR",   "Source is protected",
                               1, "HD", "DEST",               "Windows",
                               1, "HD", "DATE",           "15 OCT 2020",
                               1, "HD", "SUBM",                   "@1@",
                               1, "HD", "SUBN",                   "@2@",
                               1, "HD", "FILE",              "test.ged",
                               1, "HD", "COPR",           "Do not copy",
                               1, "HD", "GEDC",                      "",
                               2, "HD", "VERS",                 "5.5.1",
                               2, "HD", "FORM",        "Lineage-Linked",
                               1, "HD", "CHAR",                 "UTF-8",
                               1, "HD", "LANG",               "English",
                               1, "HD", "PLAC",                      "",
                               2, "HD", "FORM",                  "here",
                               1, "HD", "NOTE", "This is a gedcom file"
               ))
})


test_that("Function ADDRESS_STRUCTURE() @ L176", {
  expect_error(ADDRESS_STRUCTURE(letters[1:4]))
  expect_error(ADDRESS_STRUCTURE("address", address_city = 1:2))
  expect_error(ADDRESS_STRUCTURE("address", address_state = 1:2))
  expect_error(ADDRESS_STRUCTURE("address", address_postal_code = 1:2))
  expect_error(ADDRESS_STRUCTURE("address", phone_number = 1:4))
  expect_error(ADDRESS_STRUCTURE("address", address_email = 1:4))
  expect_error(ADDRESS_STRUCTURE("address", address_fax = 1:4))
  expect_error(ADDRESS_STRUCTURE("address", address_web_page = 1:4))
  expect_error(ADDRESS_STRUCTURE(paste0(rep("a", 61), collapse = "")))
  expect_error(ADDRESS_STRUCTURE("address", address_city = paste0(rep("a", 61), collapse = "")))
  expect_error(ADDRESS_STRUCTURE("address", address_state = paste0(rep("a", 61), collapse = "")))
  expect_error(ADDRESS_STRUCTURE("address", address_postal_code = paste0(rep("a", 11), collapse = "")))
  expect_error(ADDRESS_STRUCTURE("address", address_country = paste0(rep("a", 61), collapse = "")))
  expect_error(ADDRESS_STRUCTURE("address", address_web_page = paste0(rep("a", 121), collapse = "")))
  expect_equal(ADDRESS_STRUCTURE(), tibble::tibble())
  expect_equal(ADDRESS_STRUCTURE("Road name"),
               tibble::tribble(~level,   ~tag,      ~value,
                               0, "ADDR", "",
                               1, "ADR1", "Road name"
               ))
  
  expect_equal(ADDRESS_STRUCTURE(letters[1:3]),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "ADDR",    "",
                               1, "ADR1",    "a",
                               1, "ADR2",    "b",
                               1, "ADR3",    "c"
               ))
  
  expect_equal(ADDRESS_STRUCTURE(letters[1:2], address_country = "UK"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "ADDR",    "",
                               1, "ADR1",    "a",
                               1, "ADR2",    "b",
                               1, "CTRY",   "UK"
               ))
})


test_that("Function ASSOCIATION_STRUCTURE() @ L255", {
  expect_error(ASSOCIATION_STRUCTURE())
  expect_error(ASSOCIATION_STRUCTURE("@1@"))
  expect_error(ASSOCIATION_STRUCTURE(c("@1@", "@2@"), "Godfather"))
  
  expect_equal(ASSOCIATION_STRUCTURE("@I1@", "Godfather"),
               tibble::tribble(~level,   ~tag,      ~value,
                               0, "ASSO",      "@I1@",
                               1, "RELA", "Godfather"
               ))
  
  expect_equal(ASSOCIATION_STRUCTURE("@I1@", "Father", 
                                     notes = list(NOTE_STRUCTURE(submitter_text = "This is a note"))), 
               tibble::tribble(~level,   ~tag,              ~value,
                               0, "ASSO",              "@I1@",
                               1, "RELA",            "Father",
                               1, "NOTE",    "This is a note"
               ))
})


test_that("Function CHANGE_DATE() @ L313", {
  expect_equal(CHANGE_DATE(),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "CHAN", "",
                               1, "DATE", toupper(format(Sys.Date(), "%d %b %Y"))
               ))
                               
  expect_equal(CHANGE_DATE(date_exact(5, 10, 1990)),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "CHAN", "",
                               1, "DATE", "5 OCT 1990"
               ))
                               
  expect_equal(CHANGE_DATE(date_exact(18, 12, 2008), time_value = "11:00:08.56"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "CHAN", "",
                               1, "DATE", "18 DEC 2008",
                               2, "TIME", "11:00:08.56"
               ))
                               
  expect_equal(CHANGE_DATE(date_exact(5, 10, 1990), "10:34:56", 
                           notes = list(NOTE_STRUCTURE(submitter_text = "Note 1"),
                                        NOTE_STRUCTURE(submitter_text = "Note 2"))),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "CHAN", "",
                               1, "DATE", "5 OCT 1990",
                               2, "TIME", "10:34:56",
                               1, "NOTE", "Note 1",
                               1, "NOTE", "Note 2"
               ))
})


test_that("Function CHILD_TO_FAMILY_LINK() @ L353", {
  expect_error(CHILD_TO_FAMILY_LINK())
  expect_error(CHILD_TO_FAMILY_LINK("@1@", pedigree_linkage_type = "foste"))
  
  expect_equal(CHILD_TO_FAMILY_LINK("@F1@"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "FAMC", "@F1@"
               ))
  
  expect_equal(CHILD_TO_FAMILY_LINK("@F1@", "birth"),
               tibble::tribble(~level,   ~tag,   ~value,
                               0, "FAMC",   "@F1@",
                               1, "PEDI",  "birth"
               ))
})


test_that("Function EVENT_DETAIL() @ L406", {
  expect_equal(dim(EVENT_DETAIL()), c(0, 3))
  
  expect_equal(EVENT_DETAIL(event_or_fact_classification = "Woodworking"),
               tibble::tribble(~level,   ~tag,        ~value,
                               0, "TYPE", "Woodworking"
               ))
  
  expect_equal(EVENT_DETAIL(place = PLACE_STRUCTURE("Somewhere")),
               tibble::tribble(~level,   ~tag,      ~value,
                               0, "PLAC", "Somewhere"
               ))
  
  expect_equal(EVENT_DETAIL(place = PLACE_STRUCTURE("Somewhere"), 
                            date = date_value(2008, 4, 9, about = TRUE)),
               tibble::tribble(~level,   ~tag,      ~value,
                               0, "DATE", "ABT 9 APR 2008",
                               0, "PLAC", "Somewhere"
               ))
  
  expect_equal(EVENT_DETAIL(address = ADDRESS_STRUCTURE(c("House name", "Road"))),
               tibble::tribble(~level,   ~tag,       ~value,
                               0, "ADDR", "House name",
                               1, "CONT",       "Road",
                               1, "ADR1",       "Road"
               ))
})


test_that("Function FAMILY_EVENT_DETAIL() @ L468", {
  expect_equal(dim(FAMILY_EVENT_DETAIL()), c(0, 3))  
  
  expect_equal(FAMILY_EVENT_DETAIL(husband_age_at_event = "42y"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "HUSB",     "",
                               1,  "AGE",   "42y"
               ))
  
  expect_equal(FAMILY_EVENT_DETAIL(wife_age_at_event = "40y"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "WIFE",     "",
                               1,  "AGE",   "40y"
               ))
  
  expect_equal(FAMILY_EVENT_DETAIL(husband_age_at_event = "42y", wife_age_at_event = "40y"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "HUSB",     "",
                               1,  "AGE",   "42y",
                               0, "WIFE",     "",
                               1,  "AGE",   "40y"
               ))
})


test_that("Function FAMILY_EVENT_STRUCTURE() @ L528", {
  expect_error(FAMILY_EVENT_STRUCTURE())
  expect_error(FAMILY_EVENT_STRUCTURE("TEST"))
  
  expect_equal(FAMILY_EVENT_STRUCTURE("CENS"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "CENS",     ""
               ))
  
  expect_equal(FAMILY_EVENT_STRUCTURE("EVEN"), 
               tibble::tribble(~level,   ~tag, ~value,
                               0, "EVEN",     ""
               ))
  
  expect_equal(FAMILY_EVENT_STRUCTURE("EVEN", "Random event"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "EVEN",     "Random event"
               ))
  
  expect_equal(FAMILY_EVENT_STRUCTURE("MARR", 
                                      family_event_details = FAMILY_EVENT_DETAIL(wife_age_at_event = "20y")),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "MARR",     "Y",
                               1, "WIFE",     "",
                               2, "AGE",   "20y"
               ))
})


test_that("Function INDIVIDUAL_ATTRIBUTE_STRUCTURE() @ L574", {
  expect_error(INDIVIDUAL_ATTRIBUTE_STRUCTURE())
  expect_error(INDIVIDUAL_ATTRIBUTE_STRUCTURE("TEST"))
  expect_error(INDIVIDUAL_ATTRIBUTE_STRUCTURE("FACT"))
  expect_error(INDIVIDUAL_ATTRIBUTE_STRUCTURE(c("FACT", "EDUC"), "This is a fact"))
  expect_error(INDIVIDUAL_ATTRIBUTE_STRUCTURE("FACT", "This is a fact"))
  expect_error(INDIVIDUAL_ATTRIBUTE_STRUCTURE("IDNO", 123456))
  
  expect_equal(INDIVIDUAL_ATTRIBUTE_STRUCTURE("NATI", "British"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "NATI",     "British"
               ))
  
  expect_equal(INDIVIDUAL_ATTRIBUTE_STRUCTURE("NATI", "British", INDIVIDUAL_EVENT_DETAIL(age = "0y")),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "NATI",     "British",
                               1,  "AGE",           "0y"
               ))
})


test_that("Function INDIVIDUAL_EVENT_DETAIL() @ L631", {
  expect_equal(dim(INDIVIDUAL_EVENT_DETAIL()), c(0, 3))  
  
  expect_equal(INDIVIDUAL_EVENT_DETAIL(age = "5y"),
               tibble::tribble(~level,  ~tag, ~value,
                               0, "AGE",    "5y"
               ))
})


test_that("Function INDIVIDUAL_EVENT_STRUCTURE() @ L681", {
  expect_error(INDIVIDUAL_EVENT_STRUCTURE())
  expect_error(INDIVIDUAL_EVENT_STRUCTURE("BLAH"))
  expect_error(INDIVIDUAL_EVENT_STRUCTURE("ADOP", adopted_by_which_parent = "WHO"))
  
  expect_equal(INDIVIDUAL_EVENT_STRUCTURE("BIRT"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "BIRT",    "Y"
               ))
  
  expect_equal(INDIVIDUAL_EVENT_STRUCTURE("CHRA"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "CHRA",     ""
               ))
  
  expect_equal(INDIVIDUAL_EVENT_STRUCTURE("BIRT", xref_fam = "@F4@"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "BIRT",    "Y",
                               1, "FAMC", "@F4@"
               ))
  
  expect_equal(INDIVIDUAL_EVENT_STRUCTURE("ADOP", xref_fam = "@F4@", adopted_by_which_parent = "BOTH"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "ADOP",     "",
                               1, "FAMC", "@F4@",
                               2, "ADOP", "BOTH"
               ))
})


test_that("Function MULTIMEDIA_LINK() @ L724", {
  expect_error(MULTIMEDIA_LINK("ref"))
})


test_that("Function NOTE_STRUCTURE() @ L772", {
  expect_error(NOTE_STRUCTURE(user_text = c("test1", "test2")))
  
  expect_equal(NOTE_STRUCTURE("@T1@"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "NOTE", "@T1@"
               ))
  
  expect_equal(NOTE_STRUCTURE(user_text = "test text"),
               tibble::tribble(~level,   ~tag,      ~value,
                               0, "NOTE", "test text"
               ))
  
  expect_equal(NOTE_STRUCTURE(user_text = paste0(rep("a", 248), collapse="")),
               tibble::tribble(~level,   ~tag,      ~value,
                               0, "NOTE", paste0(rep("a", 248), collapse="")
               ))
  
  expect_equal(NOTE_STRUCTURE(user_text = paste0(rep("a", 249), collapse="")),
               tibble::tribble(~level,   ~tag,      ~value,
                               0, "NOTE", paste0(rep("a", 248), collapse=""),
                               1, "CONC", "a"
               ))
  
  expect_equal(NOTE_STRUCTURE(user_text = paste0(rep("a", 992), collapse="")),
               tibble::tribble(~level,   ~tag,      ~value,
                               0, "NOTE", paste0(rep("a", 248), collapse=""),
                               1, "CONC", paste0(rep("a", 248), collapse=""),
                               1, "CONC", paste0(rep("a", 248), collapse=""),
                               1, "CONC", paste0(rep("a", 248), collapse="")
               ))
})


test_that("Function PERSONAL_NAME_PIECES() @ L827", {
  expect_equal(dim(PERSONAL_NAME_PIECES()), c(0, 3))
  
  expect_equal(PERSONAL_NAME_PIECES(name_piece_prefix = "Mr", name_piece_nickname = "J"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "NPFX",   "Mr",
                               0, "NICK",    "J"
               ))
  
  expect_equal(PERSONAL_NAME_PIECES(name_piece_prefix = "Mr", name_piece_nickname = "J",
                                    notes = list(NOTE_STRUCTURE(submitter_text = paste0(rep("a", 992), collapse="")),
                                                 NOTE_STRUCTURE(submitter_text = paste0(rep("b", 992), collapse="")))),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "NPFX",   "Mr",
                               0, "NICK",    "J",
                               0, "NOTE", paste0(rep("a", 248), collapse=""),
                               1, "CONC", paste0(rep("a", 248), collapse=""),
                               1, "CONC", paste0(rep("a", 248), collapse=""),
                               1, "CONC", paste0(rep("a", 248), collapse=""),
                               0, "NOTE", paste0(rep("b", 248), collapse=""),
                               1, "CONC", paste0(rep("b", 248), collapse=""),
                               1, "CONC", paste0(rep("b", 248), collapse=""),
                               1, "CONC", paste0(rep("b", 248), collapse="")
               ))
})


test_that("Function PERSONAL_NAME_STRUCTURE() @ L926", {
  expect_error(PERSONAL_NAME_STRUCTURE())
  expect_error(
    PERSONAL_NAME_STRUCTURE("Joe Bloggs", 
                            name_phonetic_variation = c("Joe Blogs", "Jo Bloggs"))
  )
  expect_error(
    PERSONAL_NAME_STRUCTURE("Joe Bloggs", 
                            name_phonetic_variation = c("Joe Blogs", "Jo Bloggs"),
                            phonetisation_method = "Can't spell")
  )
  expect_error(
    PERSONAL_NAME_STRUCTURE("Joe Bloggs", 
                            name_phonetic_variation = c("Joe Blogs", "Jo Bloggs"),
                            phonetisation_method = c("Can't spell", "Can't spell"),
                            phonetic_name_pieces = list(PERSONAL_NAME_PIECES(name_piece_given = "Joe", 
                                                                             name_piece_surname = "Blogs")))
  )
  
  expect_equal(PERSONAL_NAME_STRUCTURE("Joe /Bloggs/", 
                                       name_pieces = PERSONAL_NAME_PIECES(name_piece_prefix = "Mr",
                                                                          name_piece_surname = "Bloggs")),
               tibble::tribble(~level,   ~tag,         ~value,
                               0, "NAME", "Joe /Bloggs/",
                               1, "NPFX",           "Mr",
                               1, "SURN",       "Bloggs"
               ))
  
  expect_equal(PERSONAL_NAME_STRUCTURE("Joe Bloggs", 
                                       name_phonetic_variation = c("Joe Blogs", "Jo Bloggs"),
                                       phonetisation_method = c("Can't spell", "Can't spell")),
               tibble::tribble(~level,   ~tag,         ~value,
                               0, "NAME",   "Joe Bloggs",
                               1, "FONE",    "Joe Blogs",
                               2, "TYPE",  "Can't spell",
                               1, "FONE",    "Jo Bloggs",
                               2, "TYPE",  "Can't spell"
               ))
  
  expect_equal(PERSONAL_NAME_STRUCTURE("Joe Bloggs", 
                                       name_phonetic_variation = c("Joe Blogs", "Jo Bloggs"),
                                       phonetisation_method = c("Can't spell", "Can't spell"),
                                       phonetic_name_pieces = 
                                         list(PERSONAL_NAME_PIECES(name_piece_given = "Joe", 
                                                                   name_piece_surname = "Blogs"),
                                              PERSONAL_NAME_PIECES(name_piece_given = "Jo",
                                                                   name_piece_surname = "Bloggs"))),
               tibble::tribble(~level,   ~tag,         ~value,
                               0, "NAME",   "Joe Bloggs",
                               1, "FONE",    "Joe Blogs",
                               2, "TYPE",  "Can't spell",
                               2, "GIVN",          "Joe",
                               2, "SURN",        "Blogs",
                               1, "FONE",    "Jo Bloggs",
                               2, "TYPE",  "Can't spell",
                               2, "GIVN",           "Jo",
                               2, "SURN",       "Bloggs"
               ))
})


test_that("Function PLACE_STRUCTURE() @ L1022", {
  expect_error(PLACE_STRUCTURE())
  expect_error(PLACE_STRUCTURE("Here", place_latitude = "N51.5", place_longitude = "E0.0"))
  expect_error(
    PLACE_STRUCTURE("London", 
                    place_phonetic_variation = c("Lundon", "Lundun"))
  )
  expect_error(
    PLACE_STRUCTURE("London", 
                    place_phonetic_variation = c("Lundon", "Lundun"),
                    phonetisation_method = "English accent")
  )
  
  expect_equal(PLACE_STRUCTURE("Greenwich", 
                               place_phonetic_variation = c("Grenidge", "Grenich"),
                               phonetisation_method = c("English accent", "English accent"),
                               place_latitude = "N51.5",
                               place_longitude = "E0.00"),
               tibble::tribble(~level,   ~tag,           ~value,
                               0, "PLAC",      "Greenwich",
                               1, "FONE",       "Grenidge",
                               2, "TYPE", "English accent",
                               1, "FONE",        "Grenich",
                               2, "TYPE", "English accent",
                               1,  "MAP",               "",
                               2, "LATI",          "N51.5",
                               2, "LONG",           "E0.00"
               ))
})


test_that("Function SOURCE_CITATION() @ L1113", {
  expect_equal(SOURCE_CITATION("@S1@"),
               tibble::tribble(
                 ~level,   ~tag, ~value,
                 0, "SOUR", "@S1@"
               ))
  
  expect_equal(SOURCE_CITATION("@S1@", where_within_source = 3, event_type_cited_from = "event"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "SOUR",  "@S1@",
                               1, "PAGE",     "3",
                               1, "EVEN", "event"
               ))
  
  expect_equal(SOURCE_CITATION("@S1@", where_within_source = 3, role_in_event = "a role"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "SOUR",  "@S1@",
                               1, "PAGE",     "3"
               ))
  
  expect_equal(SOURCE_CITATION("@S1@", where_within_source = 3, 
                               event_type_cited_from = "event", 
                               role_in_event = "a role"),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "SOUR",   "@S1@",
                               1, "PAGE",      "3",
                               1, "EVEN",  "event",
                               2, "ROLE", "a role"
               ))
})


test_that("Function SOURCE_REPOSITORY_CITATION() @ L1171", {
  expect_error(SOURCE_REPOSITORY_CITATION())
  expect_error(SOURCE_REPOSITORY_CITATION("@R1@", source_call_number = c("123", "456"))
  
  expect_equal(SOURCE_REPOSITORY_CITATION("@R1@", source_call_number = 123),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "REPO", "@R1@",
                               1, "CALN",  "123"
               ))
})


test_that("Function SPOUSE_TO_FAMILY_LINK() @ L1203", {
  expect_error(SPOUSE_TO_FAMILY_LINK())
  
  expect_equal(SPOUSE_TO_FAMILY_LINK("@F2@", list(NOTE_STRUCTURE(submitter_text = "test"))),
               tibble::tribble(~level,   ~tag, ~value,
                               0, "FAMS", "@F2@",
                               1, "NOTE",  "test"
               ))
})

