# Generated by roxytest: Do not edit by hand!

context("File R/edit_individual_names.R: @tests")

test_that("Function remove_individual_name() @ L191", {
  expect_equal(gedcom(subm()) %>% 
                 add_individual(),
               gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual_names("Joe Bloggs", given = "Joe", surname = "Bloggs") %>% 
                 remove_individual_name("Joe Bloggs"))
})


test_that("Function remove_individual_name_var() @ L221", {
  expect_equal(gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual_names("Joe Bloggs", given = "Joe", surname = "Bloggs"),
               gedcom(subm()) %>% 
                 add_individual() %>% 
                 add_individual_names("Joe Bloggs", given = "Joe", surname = "Bloggs") %>% 
                 add_individual_names_var("Joe Bloggs", "Jo Blogs", "spelling error") %>% 
                 remove_individual_name_var("Jo Blogs"))
})

