# Generated by roxytest: Do not edit by hand!

context("File R/edit_note.R: @tests")

test_that("Function remove_note() @ L45", {
  expect_equal(gedcom(subm()),
               gedcom(subm()) %>% add_note("text") %>% remove_note())
})

