# Generated by roxytest: Do not edit by hand!

context("File R/dates.R: @tests")

test_that("Function date_exact() @ L19", {
  expect_equal(date_exact(12), character())
  expect_equal(date_exact(12, 8), character())
  expect_equal(date_exact(12, 8, 2005), "12 AUG 2005")
})


test_that("Function date_value() @ L66", {
  expect_equal(date_value(2005), "2005")
  expect_equal(date_value(2005, 1), "JAN 2005")
  expect_equal(date_value(2005, 1, 14), "14 JAN 2005")
  expect_equal(date_value(2005, after = TRUE), "AFT 2005")
  expect_equal(date_value(2010, before = TRUE), "BEF 2010")
  expect_equal(date_value(2005, 10, 14, before = TRUE), "BEF 14 OCT 2005")
  expect_equal(date_value(1900, 6, 30, from = TRUE), "FROM 30 JUN 1900")
  expect_equal(date_value(2000, 1, 1, to = TRUE), "TO 1 JAN 2000")
  expect_equal(date_value(2005, 1, 14, 2006, 7, 9, from = TRUE, to = TRUE), "FROM 14 JAN 2005 TO 9 JUL 2006")
  expect_equal(date_value(2005, 1, 14, 2006, 7, 9, between = TRUE), "BET 14 JAN 2005 AND 9 JUL 2006")
  expect_equal(date_value(2005, 1, 14, calc = TRUE), "CAL 14 JAN 2005")
  expect_equal(date_value(2005, est = TRUE), "EST 2005")
  expect_equal(date_value(2005, 1, about = TRUE), "ABT JAN 2005")
})


test_that("Function date_period() @ L142", {
  expect_equal(date_period(2005), "FROM 2005")
  expect_equal(date_period(2005, 1), "FROM JAN 2005")
  expect_equal(date_period(2005, 1, 14), "FROM 14 JAN 2005")
  expect_equal(date_period(2005, to = TRUE), "TO 2005")
  expect_equal(date_period(2010, 6, to = TRUE), "TO JUN 2010")
  expect_equal(date_period(2005, 10, 14, 2008, 9), "FROM 14 OCT 2005 TO SEP 2008")
  expect_equal(date_period(1900, 6, 30, 1901), "FROM 30 JUN 1900 TO 1901")
})

