# Generated by roxytest: Do not edit by hand!


test_that("Function split_gedcom() @ L133", {
  expect_snapshot_value(split_gedcom(sample555, c("@I1@","@S1@")), "json2")
  expect_snapshot_value(split_gedcom(sample555, c("@I1@","@S1@"), FALSE), "json2")
})

