# Generated by roxytest: Do not edit by hand!

# File R/note.R: @tests

test_that("Function remove_note() @ L38", {
  expect_equal(gedcom(subm()),
               gedcom(subm()) |> add_note("text") |> remove_note())
})

