# Generated by roxytest: Do not edit by hand!

context("File R/edit_individual_links.R: @tests")

test_that("Function add_individual_association() @ L24", {
  expect_snapshot_value(gedcom(subm("Me")) %>% 
                          add_individual() %>% 
                          add_individual_names("Joe Bloggs") %>% 
                          add_individual() %>% 
                          add_individual_names("Jimmy Bloggs") %>%
                          add_individual_association(associated_with = "Joe", association = "Friend") %>% 
                          remove_dates_for_tests(), "json2")
})

